// icons.js
import {
  faCoffee,
  faCar,
  faMusic,
  faHeart,
  faStar,
  faSmile,
  faSun,
  faMoon,
  faLeaf,
  faPlane,
  faBasketballBall,
  faCamera,
  faCode,
  faBook,
  faGlobe,
  faHome,
  faClipboard,
  faRocket,
  faRunning,
  faUmbrella,
  faMobile,
  faLaptop,
  faWifi,
  faFilm,
  faGamepad,
  faShoppingCart,
  faPizzaSlice,
  faBeer,
  faBicycle,
  faChess,
  faClock,
  faMicrophone,
  faHeadphones,
  faKeyboard,
  faMouse,
  faTv,
  faTools,
  faTruck,
  faBuilding,
  faTrain,
  faTree,
  faFlag,
  faBalanceScale,
  faMoneyBill,
  faBug,
  faComments,
  faEnvelope,
  faLock,
  faUnlock,
  faUser,
} from '@fortawesome/free-solid-svg-icons';

export const iconList = [
  { value: 'coffee', icon: faCoffee },
  { value: 'car', icon: faCar },
  { value: 'music', icon: faMusic },
  { value: 'heart', icon: faHeart },
  { value: 'star', icon: faStar },
  { value: 'smile', icon: faSmile },
  { value: 'sun', icon: faSun },
  { value: 'moon', icon: faMoon },
  { value: 'leaf', icon: faLeaf },
  { value: 'plane', icon: faPlane },
  { value: 'basketball', icon: faBasketballBall },
  { value: 'camera', icon: faCamera },
  { value: 'code', icon: faCode },
  { value: 'book', icon: faBook },
  { value: 'globe', icon: faGlobe },
  { value: 'home', icon: faHome },
  { value: 'clipboard', icon: faClipboard },
  { value: 'rocket', icon: faRocket },
  { value: 'running', icon: faRunning },
  { value: 'umbrella', icon: faUmbrella },
  { value: 'mobile', icon: faMobile },
  { value: 'laptop', icon: faLaptop },
  { value: 'wifi', icon: faWifi },
  { value: 'film', icon: faFilm },
  { value: 'gamepad', icon: faGamepad },
  { value: 'shopping-cart', icon: faShoppingCart },
  { value: 'pizza-slice', icon: faPizzaSlice },
  { value: 'beer', icon: faBeer },
  { value: 'bicycle', icon: faBicycle },
  { value: 'chess', icon: faChess },
  { value: 'clock', icon: faClock },
  { value: 'microphone', icon: faMicrophone },
  { value: 'headphones', icon: faHeadphones },
  { value: 'keyboard', icon: faKeyboard },
  { value: 'mouse', icon: faMouse },
  { value: 'tv', icon: faTv },
  { value: 'tools', icon: faTools },
  { value: 'truck', icon: faTruck },
  { value: 'building', icon: faBuilding },
  { value: 'train', icon: faTrain },
  { value: 'tree', icon: faTree },
  { value: 'flag', icon: faFlag },
  { value: 'balance-scale', icon: faBalanceScale },
  { value: 'money-bill', icon: faMoneyBill },
  { value: 'bug', icon: faBug },
  { value: 'comments', icon: faComments },
  { value: 'envelope', icon: faEnvelope },
  { value: 'lock', icon: faLock },
  { value: 'unlock', icon: faUnlock },
  { value: 'user', icon: faUser },
];
